// <auto-generated />
using System;
using App1.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App1.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250921163630_AddUserId")]
    partial class AddUserId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App1.Domain.User", b =>
                {
                    b.Property<Guid>("Key")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Key");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Key = new Guid("11111111-1111-1111-1111-111111111111"),
                            FirstName = "John",
                            Id = 1,
                            LastName = "Doe"
                        },
                        new
                        {
                            Key = new Guid("22222222-2222-2222-2222-222222222222"),
                            FirstName = "Jane",
                            Id = 2,
                            LastName = "Smith"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
